### ISSUE TITLE
[Full stack] Setting up React, Express, and MongoDB all together

### ISSUE THREAD

**Issue by hhelb** [remarkablemark/tutorials#1]
Title: [Full stack] Setting React Express NodeJs and MongoDB all together

Thanks to your extremely clear YouTube tutorials, I was able to sharpen my knowledge in the client side and server side rendering using React.
Now maybe let's go one step further with a full stack example by adding a database like MongoDB?
You could explain how to get the data from the DB and use them as props (?) in a react component?
It would be very interesting with your approach of teaching to understand how to get data from a database and to do a basic CRUD with them, and rendering with React.

I found a [tutorial](https://hashnode.com/post/react-tutorial-using-mern-stack-ciiyus9m700qqge53mer0isxz) (too old maybe?) about the [MERN](http://mern.io) stack which uses the techs above and was developed by the hashnode community.

I your opinion is it a good think to go fullstack with react as the view for a basic CRUD project for example? a more complicated one like a social network? 

I really have appreciated your react tutorials and hope you'll continue your awesome video format (which in my opinion is the best format to teach code :wink: ) !

Thank you and keep going!

### Todo:

- [x] [MongoDB] How to install on Mac (#2)
- [x] [Mongoose] How to connect to MongoDB (#3)
- [ ] [Mongoose] Set up in Express (#4)

**Comment by remarkablemark** [comment]
Thanks @hhelb for the request!

This tutorial does seem a bit heavy--perhaps we can modularize it a bit?  I can create separate tutorials on MongoDB and then add it to the React app or simply use mock data like [faker](https://github.com/marak/Faker.js) in the app.

I think MERN is pretty awesome. You're right in that some of the links and libraries in the tutorial are outdated, but the app should still work.

If CRUD is what you're looking for, then the best way to learn about CRUD is to build a [todo list](http://todomvc.com). That too should be its own separate tutorial as well. In that case, I may also want to add [Redux](https://github.com/reactjs/redux) to the app.

Given that I can only make one tutorial at a time, what would you say is the most important?
- Fetching and passing data on the server-side
  - with MongoDB\* or
  - with Faker
- CRUD
  - Todo list or
  - Redux\* then todo list

*Remember that MongoDB will be its own isolated tutorial.
*I may or may not go in-depth on Redux since there are already many good tutorials out there.

**Comment by hhelb** [comment]
Thanks @remarkablemark for your reply! 

I didn't know about faker thank you, it will be surely useful! 

Personally, I think that both points would be very interesting to see. 
But I have some troubles to picture the following: 
- How, once we have fetched the data from the server, do we pass it to the "View", in our case a react component, same thing in case we want to post some data to the DB via a form ([react form](https://github.com/korbin/react-form)?) or whatever. 

I am sorry, maybe the question is a bit stupid or maybe I have missed something, but it's a point that I really don't get.. 

So in order to clarify this what would you suggest? 
( I am currently doing some reverse engineering on the mern boilerplate project and [reactGo](https://github.com/reactGo/reactGo) in order to understand the logic behind the routes and the matching between the express routes and the react routes, it's time consuming but i really like it!) 

Thank you for your time!

**Comment by remarkablemark** [comment]
**Question:** How do we pass server data to our React component (view)?

**Answer:** With [props](https://facebook.github.io/react/docs/components-and-props.html). See how I do it in the [video](https://youtu.be/qwgNv27366Q?t=29). I also explain the same step in my blog [post](https://medium.com/@remarkablemark/passing-props-in-a-universal-react-web-app-c52aca48c36b#bfd7).

---

**Question:** How do we send client data to the server and save it to the database?

**Answer:** On the client-side, create a form or an AJAX request that sends data to a POST route. On the server-side, create the POST route that receives the data and performs the backend logic (i.e., save to database). See very basic example:

``` js
// server.js
var express = require('express');
var bodyParser = require('body-parser');
var app = express();

// the middleware will parse your form data to JS object
app.use(bodyParser.urlencoded({ extended: true })); 

// index route
app.get('/', function(request, response) {
    response.send(`
        <form action="/your-post-route" method="post">
            <input type="text" name="username" value="hhelb" />
            <input type="submit" value="Submit" />
        </form>
    `);
});

// post route
app.post('/your-post-route', function(request, response) {
    console.log(request.body.username); // hhelb
    // perform your database logic
});

app.listen(8080);
```

**Comment by hhelb** [comment]
Remarkable! Thank you @remarkablemark . 

If you're still interested, maybe your next tutorials would first be about "**fetching and passing data on the server-side**" with **_Mongo_** since it's one of the most popular database , and in a second time a CRUD using **_Mongo_** (and **_Redux_**)? 
What do you think? Since nowadays these tech are very popular, would it be relevant ? 

Cheers.

**Comment by remarkablemark** [comment]
So I think I'll look into making tutorials for the 3 referenced issues for now (so I don't get overwhelmed).

If you feel there's a tutorial that's more important, we can probably swap one with the more important one. As always, I'll try my best to get them done, but the time frame depends on my schedule and how much free time I have (I also have other tutorials that I'm working on concurrently). Thanks for understanding!

**Comment by hhelb** [comment]
Thanks, It would be awesome!

Keep me in touch !

**Comment by remarkablemark** [comment]
[How to install MongoDB on Mac](https://b.remarkabl.org/2fqg3ba) is published!

**Comment by frempongandrews** [comment]
This would be awesome!! There are few articles and no videos on the topic whatsoever.  Looking forward to it ;)

**Comment by remarkablemark** [comment]
Progress update: I've been swamped with work for the past few weeks, but I plan to finish #3 sometime next week. Thanks everyone for being patient. Also, Happy New Year!

**Comment by remarkablemark** [comment]
Update: [How to connect to MongoDB with mongoose](https://b.remarkabl.org/2mzHcbN) has been published.

Thanks so much for being patient. I know I've been bogged down by work and other videos, but I'm going to dedicate my time to completing the rest of the videos.
